# on:
#   push:
#     branches:
#       - main
on:
  issues:
    types:
      - assigned

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub dispatch event
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.API_REQUEST_TOKEN }}
          repository: Saki-htr/fjord-choice
          event-type: bootcamp-issue-assigned
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
        # run: |
        #   curl --request POST 'https://api.github.com/repos/Saki-htr/fjord-choice/dispatches' \
        #   --header 'Authorization: Bearer ${{secrets.API_REQUEST_TOKEN}}' \
        #   --header 'Content-Type: application/json' \
        #   --data-raw '{
        #     "event_type": "bootcamp-issue-assigned"
        #   }'
